### ISSUE TITLE
bug associé à la variable lgrass NextAccroiss

### ISSUE THREAD

**Issue by traquet** [traquet/lgrass#1]
Sur la branche Debug, et le script 'lgrass.lpy', NextAccroiss est une variable locale qui apparaît uniquement dans le bloc 1320-1330. Sous les conditions initiales présentes dans le scénario 'test' (le dernier) du fichier 'inputs/plan_simulation.csv', voici l'erreur obtenue après itérations de 1211°Cj :   

`Traceback (most recent call last):
  File "C:/Users/thibault/Modelisation/lgrass/lgrass/lgrass_batch_simpraise.py", line 149, in <module>
    runlsystem(plan, 11, 1)
  File "C:/Users/thibault/Modelisation/lgrass/lgrass/lgrass_batch_simpraise.py", line 94, in runlsystem
    lstring = lsystem.derive(lstring, dd, 1)
  File "<string>", line 1330, in __p_0_5_Feuille_X_X_apex_X_phytomere_
UnboundLocalError: local variable 'NextAccroiss' referenced before assignment`

Les pistes de recherche : il existe un cas dans lequel la variable NextAccroiss n'est pas déclarée, à la ligne 1326 : 

`if ((X.Taillegaine>=Taille_finale_gaine[X.id_plante][X.id_talle][X.id_rang-1] +13) and (X.Phase=='visible')):`

Il manque ici le cas 
`if ((X.Taillegaine>=Taille_finale_gaine[X.id_plante][X.id_talle][X.id_rang-1] +13) and (X.Phase=='cachee')):`

C'est un cas qui n'est apparemment jamais censé se produire, mais il se produit sous ces conditions initiales. Les 'option_caribu' et 'option_mophogenetic_regulation_by_carbone' sont notamment activées. Les valeurs d'entrée en 'mean_temperature' et 'PAR_incident' du fichier 'inputs/meteo_controlled_conditions_ray.csv' sont donc à prendre en compte, car le bug ne se produit pas (ou du moins pas sur le nombre d'itérations souhaité) pour toutes les valeurs que l'on pourrait y entrer. Néanmois aucune idée actuelle d'une éventuelle plage de valeurs pour laquelle le bug se produit

**Comment by traquet** [comment]
(Je lance lgrass via le script 'lgrass_batch_simpraise.py', la gestion des options s'y trouve)
